name: ML in prod Project ci cd docker
on:
  push:
    branches: 
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        
    - uses: actions/checkout@v3

    - name: Set up and run necessary Docker Compose services
      run: docker-compose -f docker-compose.yml up -d --no-deps chrome web

    - name: Check if Chrome is up and running
      run: |
        until docker-compose -f docker-compose.yml exec -T web curl -f http://chrome:4444/wd/hub/status; do
            echo "Waiting for Chrome service..."
            sleep 5
        done

    - name: Run unit tests
      run: docker-compose -f docker-compose.yml run --no-deps unit-test

    - name: Run integration tests
      run: docker-compose -f docker-compose.yml run --no-deps integration-test

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose -f docker-compose.yml down

  build-and-push-docker-image:
   runs-on: ubuntu-22.04
   needs: test
   # steps to perform in job
   steps:
     - name: Checkout code
       uses: actions/checkout@v2.5.0

     - name: Log in to Docker Hub
       uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

     - name: Build Docker image and push backend
       run: |
        docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/project-ml-prod:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-ml-prod:latest
