name: ML in prod Project ci cd docker
on:
  push:
    branches: 
      - staging
      - dev

jobs:
  build-and-push-docker-image:
   runs-on: ubuntu-22.04
  
   # steps to perform in job
   steps:
     - name: Checkout code
       uses: actions/checkout@v2.5.0

     - name: Log in to Docker Hub
       uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

     - name: Build Docker image and push backend
       run: |
        docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/project-ml-prod:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-ml-prod:latest
